### ISSUE TITLE
Possibility to change license to LGPL?

### ISSUE THREAD

**Issue by finsberg** [ivhak/cardiac-fibers#1]
Hi Iver,

I wanted to try to package your code into a python library so that it becomes more accessible for others. In doing that, I was wondering if it would be possible to change the license from GPL to LGPL.  By using LGPL instead of GPL you allow other software to use your software without needing to license it under the same license. This means that for example companies can use your software (i.e link it), but any modification to your software need to still be open. 

With GPL, anyone that uses your software need to also license their software under GPL which is very restrictive I think.

**Comment by ivhak** [comment]
Hi Henrik,

I forgot you brought this up earlier. It seems like a good idea! Will take care of it as soon as possible.

**Comment by ivhak** [comment]
Changed as per commit [cf9d88c](https://github.com/ivhak/cardiac-fibers/commit/cf9d88c0045973e29096e912ffc074e9cb2b6a38).
